### ISSUE TITLE
Configurable retry mechanism in PulsarTemplate sendAsync

### ISSUE THREAD

**Issue by sobychacko** [spring-projects-experimental/spring-pulsar#16]
Currently `PulsarTemplate` provides both `send` and `sendAsync` methods.

As a developer, I would like the following use case implemented.

I want to call the `sendAsync` method, but if the sending fails, I would like the framework to add a retry based on some configurations (preferably with a backoff). Currently, the only option is that the method returns a `CompletableFuture` back to the user and the user can decide what to do with the future. While that implementation has some valid use cases, I think having a re-tryable `sendAsync` will be convenient. 

Scenario - I set the `batchingMaxMessages` and `batchingMaxPublishDelayMicros` on the producer to their defaults (`1000` and `TimeUnit.MILLISECONDS.toMicros(1)` respectively). Assume that I produce 100 records every microsecond and some of them happen to fail for whatever reason. As a developer, I do not want to resend them if the errors are due to some transient reasons, rather I would like the framework to help me re-sending them.

**Comment by onobc** [comment]
### Batch/Chunking impl note

Because these are producer level configuration options we will need to create the concept of `ProducerBuilderCustomizer` and then pass them down upon creation. Similar to what we are doing w/ the `TypedMessageBuilderCustomizer` currently. 

The fluent template will lend itself well to allowing the users to specify the option(s). Will need a bit of work to pass that down into the DefaultProducerFactory. 

We will need to decide whether to expose the entire builder or just the fine grained levers we want to.


#### Option1: Expose the entire builder
```java
public SendMessageSpec<T> producerCustomizedWith(ProdcuerBuilderCustomizer<T> customizer) {
	producerCustomizers.add(customizer);
	return this;
}
```

#### Option 2: Expose only those options we want 
```java
public SendMessageSpec<T> withBatching(boolean enabled) {
	producerCustomizers.add((producerBuilder -> producerBuilder.enableBatching(enabled)));
	return this;
}

public SendMessageSpec<T> withChunking(boolean enabled) {
	producerCustomizers.add((producerBuilder -> producerBuilder.enableChunking(enabled)));
	return this;
}
```

Tradeoffs include:
* **Option1**
  * (➕) full power to users / less maintenance feature requests for us to add
  * (➖) more possible for user to shoot themselves in the foot w/ too much power 
* **Option2**
  * (➕) less power to users / more maintenance feature requests for us to add
  * (➖) less possible for user to shoot themselves in the foot w/ too much power 


@sobychacko @alpreu what option should we go w/? I am in favor of `option1` because I feel the validation of the internal pulsar producer is fairly extensive thus minimizing the risk of them "shooting themselves in the foot". Wdyt?

**Comment by alpreu** [comment]
My feel would also be to go with option 1

**Comment by onobc** [comment]
**[BadTicketMovingHygeine]** 🖐🏻 (me).....

The batching/chunking config was split into its own ticket but it was the one that had some comments in this ticket about it. In hindsight I should have left that in here and moved the "retry" into another ticket.

**Comment by sobychacko** [comment]
Since this issue was created, the producer side of the code in Spring Pulsar is much more advanced. Therefore closing for the time being.
