### ISSUE TITLE
Add ability to pause/resume consumer

### ISSUE THREAD

**Issue by pkokoshnikov** [spring-projects-experimental/spring-pulsar#286]
I want to be able in some situations to pause consuming. For example if service responds for example 500, it would be better to stop to do requests. Wait for example 10s and try again. If one request is ok then we can resume consuming.

**Comment by sobychacko** [comment]
@pkokoshnikov That certainly sounds like a very interesting use case. We will look into it as a new feature on the container side that the consumer uses.

**Comment by sobychacko** [comment]
@pkokoshnikov We added the pause/resume feature. Please look at the latest commit and the [documentation](https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#_pausing_and_resuming_message_listener_containers). 

If you like Spring Pulsar so far, please feel free to [star](https://github.com/spring-projects-experimental/spring-pulsar/stargazers) the repo:-) And more importantly, continue to give us feedback (or feature requests) so that we can improve things further. You can also contribute any bug fixes or features in the form of pull requests.
