### ISSUE TITLE
Exception in listener thread is not shown in log

### ISSUE THREAD

**Issue by pkokoshnikov** [spring-projects-experimental/spring-pulsar#291]
```
    @PulsarListener(subscriptionName = "hello-pulsar-subscription",
            topics = "persistent://public/dev/partitioned-topic",
            subscriptionType = SubscriptionType.Shared
    )
    public void listen(String message, Acknowledgement acknowledgement) {
            System.out.println("Message Received: " + message);
            throw new RuntimeException("Exception");
    }

    @Bean
    public PulsarTopic topic() {
        return PulsarTopic.builder("persistent://public/dev/partitioned-topic")
                .numberOfPartitions(4)
                .build();
    }    
```

**Comment by pkokoshnikov** [comment]
Should it commit offset if exception is occurred

**Comment by sobychacko** [comment]
@pkokoshnikov In your `PulsarListener` you are relying on the default framework behavior of message consumption and acknowledgment. Let's look at the details. Spring Pulsar provides two ways of consuming messages in `PulsarListener` - in record and batch modes. In your example, you are using a record listener, i.e., you are consuming a single record per method invocation. Let's keep our focus only on this record mode for now. Let's also rewrite your `PulsarListener` method as below without the `Acknoledgement` object.
```
@PulsarListener(subscriptionName = "hello-pulsar-subscription",
            topics = "persistent://public/dev/partitioned-topic",
            subscriptionType = SubscriptionType.Shared
    )
public void listen(String message) {
    System.out.println("Message Received: " + message);
    throw new RuntimeException("Exception");
}
```

The `PulsarListener` method throws an exception to the caller. The caller, in this case, is the message listener container in the framework. Before we look at the details of what the container does with this exception, let us back up a little bit and see how the container consumes data from Pulsar itself before handing it over to the listener method. The container consumes data from the Pulsar topic using `batchReceive` in a separate thread from the main processing thread of the application. Assume that this `batchReceive` returned ten records in the call. The container detects that your listener method is a record-based listener since it receives a non-collection object. Then the container hands off a single record at a time from the ten that we received, and for each of them, invoke the listener method. Based on your example, the listener method throws the exception and returns to the container. The container catches the exception and marks the record as something to be negatively acknowledged. It then goes through all ten records from the batch and invokes the listener. At the end of this process, we have two collections - one that contains the records that didn't throw any exception and another one that contains the records that failed. At this point, the container takes the first collection and acknowledges all of them; it takes the second set and negatively acknowledges (nack) all of them. In your example, you only have the second collection since all of the records throw an exception.

This is the default behavior, and it is what you are observing. The exception from the listener method is never thrown back to the application in the default case but instead handled by the framework. 

If you do not like this approach, you can disable auto acking/nacking in the framework and do manual acknowledgment. Here is an example with some pseudo code.

```
@PulsarListener(subscriptionName = "hello-pulsar-subscription",
            topics = "persistent://public/dev/partitioned-topic",
            subscriptionType = SubscriptionType.Shared,
            ackMode = AckMode.MANUAL
    )
public void listen(String message, Acknowledgement acknowledgement) {
    System.out.println("Message Received: " + message);
    try {
      if (no exception condition) {
         acknowledgement.acknowledge();
     }
     else {
        //log the exception
        throw new RuntimeException("Exception");
     }
    }
    catch (Exception e) {
       acknowledgement.nack(); 
    }
}
```

Note that we have an `ackMode` property provided as part of the `PulsarListener` annotation. When you set this property to  `AckMode.MANUAL`, then the framework (aka the container), stays away from any message acknowledgment, and it is completely up to the application's responsibility to do any message acking and nacking. As you can see from the pseudo-code above, if the business logic doesn't throw any exceptions, you can call `acknowledge()` and if it throws an exception, then call `nack` on the `Acknowledgement` object. You can log the exception if you want to monitor what's going on. 

When negatively acknowledging a message, Pulsar, by default, will re-deliver the message after 60 seconds. You can change this default by setting the `negativeAckRedeliveryDelayMicros` property. 

More details can be found in these sections of the reference doc:
https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#_message_acknowledgment

https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#_message_redelivery_and_error_handling

Let us know what you think about this, and then we can take it from there if you need more clarification.

**Comment by pkokoshnikov** [comment]
Hi @sobychacko !

Thank you for your answer!

My main question was in, is it right way to skip unhandled exception from user listener. I would prefer that framework shows the log about exception if i forgot to catch an exception. People do mistakes. And it will be better to show it from my view point. 

Your solution with catch is correct and i already did it.
