### ISSUE TITLE
Tests are failing when running on M1 Mac

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-pulsar#57]
**Steps to reproduce:** Run `gradle clean build` on an M1 Mac.

**Possible cause:** Pulsar image running super slow because of M1 Mac?

**Workaround:** Modify the image used in https://github.com/spring-projects-experimental/spring-pulsar/blob/749f2dbb5e386f77e842af2ece547fbdc0e8f84f/spring-pulsar/src/test/java/org/springframework/pulsar/core/AbstractContainerBaseTests.java#L24
with 
```java
static final DockerImageName PULSAR_IMAGE = DockerImageName.parse("kezhenxu94/pulsar").asCompatibleSubstituteFor("apachepulsar/pulsar");
```
### Work items

1. Understand what the root cause is. What is in the alternative image that makes it work? Is there some other change we should be considering or is this just the "M1 support in general is still catching up" category?
2. Temporary stop-gap so that other users do not run into this, we could implement the above workaround automatically via Junit5 [@EnabledOnOs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-os) annotation (one for M1 and one for all others).

**Comment by alpreu** [comment]
I believe the root cause is that the standard Pulsar image running through emulation is very slow. This leads to Testcontainers startup check to time out, thus stopping further test execution.

The issue around offering ARM based images can be found here: 
https://github.com/apache/pulsar/issues/12944

And the experimental image above was built using this PR: 
https://github.com/apache/pulsar/pull/14005

I tried to re-ignite the discussion on the mailing list around this topic and looped in colleagues as well.

For the time being, I think it's a good idea to enable the workaround using the JUnit annotation as you described above.

**Comment by onobc** [comment]
**NOTE:** As of 2.11.0 the standard Pulsar image is now able to run on Mac M1.
